version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3
jobs:
  deploy:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true    # default - false
    steps:
      - checkout
      - aws-cli/setup
#      - setup_remote_docker
#      - setup_remote_docker:
#          version: 20.10.14
      - run:
          name: Bootstrap
          command: |
            ./bin/bootstrap
      - run:
          name: Deploy
          command: |
            ./bin/deploy
workflows:
  aws-cli:
    jobs:
      - deploy