version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3
  docker: circleci/docker@2.1.4
jobs:
  deploy:
    docker:
      - image: cimg/ruby:2.7.0
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Bootstrap
          command: |
            ./bin/bootstrap
      - run:
          name: Deploy
          command: |
            ./bin/deploy
workflows:
  aws-cli:
    jobs:
      - deploy