version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3
jobs:
  deploy:
    docker:
      - image: cimg/ruby:2.7.6-node
    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker
      - run:
          name: Bootstrap
          command: |
            ./bin/bootstrap
      - run:
          name: Deploy
          command: |
            ./bin/deploy
workflows:
  aws-cli:
    jobs:
      - deploy