version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3
jobs:
  deploy:
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Bootstrap
          command: |
            ./bin/bootstrap
      - run:
          name: Deploy
          command: |
            ./bin/deploy