version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3
jobs:
  deploy:
    machine:
      image: ubuntu-2204:2022.04.2
      docker_layer_caching: true
    steps:
      - checkout
      - aws-cli/setup
#      - setup_remote_docker
      - run:
          name: Bootstrap
          command: |
            ./bin/bootstrap
      - run:
          name: Docker Context
          command: |
            docker context ls
      - run: docker info
      - run:
          name: Deploy
          command: |
            ./bin/deploy
workflows:
  aws-cli:
    jobs:
      - deploy